export const DEFAULT_PRODUCTS = [
  {
    id: "p1",
    name: "Hand-Painted Blue Pottery",
    slug: "hand-painted-blue-pottery",
    sku: "PM-DEC-001",
    category: "Traditional Crafts",
    price: 3200,
    comparePrice: 0,
    stock: 14,
    enabled: true,
    seoIndex: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDEnJcw27yqpwlpvv0CQrU-eh2amN6a_STX9AuW9cgXJq-2eUdIFlH11x2GF28_1SJx-VlCy0CQdjtwlSrrOlkXOKQSy_p3-HJ6JYC0uPwvPdO-WnQHNQsCnaUvGuVMp2jW_WtC7h2GdsnUEKhCLZ2a93apKwCK_CAtXh0KApDteHht0WtdcSIwDn8vaLc4H_a7tRjAi1R_CihbpUUlcO_T23p06vocmxpHhQqibFSGuYf3lcP4V6oWkgPulKdXpssFUXX3vFp-4DU",
    imageAlt: "Hand-painted blue Pakistani pottery vase",
    description: "Hand-painted blue pottery created by skilled Pakistani artisans.",
    seoTitle: "Hand-Painted Blue Pottery | PakMarket",
    metaDescription: "Shop authentic hand-painted blue pottery crafted by Pakistani artisans.",
  },
  {
    id: "p2",
    name: "Premium Almond Biscotti",
    slug: "premium-almond-biscotti",
    sku: "PM-FOD-002",
    category: "Food",
    price: 1250,
    comparePrice: 0,
    stock: 5,
    enabled: true,
    seoIndex: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDPriF7OxgDh9P1lww92VI5_52o9lt5okLM2-VzwOcXq126uJyEm2wshXS2CFYbNDjyxmD6j9xwM9LikrIuCpJBuFJrG4R0BBEAXJgzC-hyW68ICbA-6kNl51jtuPnhLwohPlXD9Cqrfr0l_eh_8vD94eDS2B077mQzSOeA7c6SIP91JFNGA9dGNMxRAJlhPhb9EtdcQEqbEwMA-itTsd_ZfJMibs1oDCxPOYXo6KaUZRNhNBYFxnxeKTCjlaJ75DcncKetN0f4qrA",
    imageAlt: "Premium almond biscotti cookies in a glass jar",
    description: "Crisp, small-batch almond biscotti baked by a local home bakery.",
    seoTitle: "Premium Almond Biscotti in Pakistan | PakMarket",
    metaDescription: "Order premium almond biscotti from a trusted Pakistani home bakery.",
  },
  {
    id: "p3",
    name: "Hand-Embroidered Kurta",
    slug: "hand-embroidered-kurta",
    sku: "PM-FAS-003",
    category: "Fashion",
    price: 4800,
    comparePrice: 5500,
    stock: 9,
    enabled: true,
    seoIndex: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUlWgQk76WXv_5_8XFGGKzpmz5gv4ajaYvRF_HIEmbacOYQJ6Hy_AE3nZZEJAz49JUtc4Cl1M8AcedCkTfuAWmKqc0qz4VKEpxTVWAWhgNr9UqGORmFDJpwfFEgig1Z7jT4LzGouCkn7ihiOSCGGk7DS8GfwJxLPAvt0-PwuP0rrH5JtYfN7Ed35sdjRieuSoFYwGmjIAebqZh3AZQ38pk45r_qux4vYPPOE8cT-7J8fgpHVanfS26_rW6J04xJwDuFNkCNbxS6U8",
    imageAlt: "Hand-embroidered Pakistani kurta on a hanger",
    description: "A contemporary kurta finished with traditional hand embroidery.",
    seoTitle: "Hand-Embroidered Pakistani Kurta | PakMarket",
    metaDescription: "Discover a modern Pakistani kurta with beautiful hand embroidery.",
  },
  {
    id: "p4",
    name: "Organic Soy Wax Candle",
    slug: "organic-soy-wax-candle",
    sku: "PM-HOM-004",
    category: "Home Decor",
    price: 1850,
    comparePrice: 0,
    stock: 3,
    enabled: true,
    seoIndex: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDnt484UTtaCPybNOiC9RcQz7hcdBIdo9kAfmH6JGIenwNVO4O08ScYu7NHnusSsI-N_OirWfxOt4Z8ZRCk23einHK7n1A-TwF8oy3qVNGWQgwt1TmJDNfK3oZazwkTj8O2NLRIt019TEE_3pw2c3H7G2Q0PwYKolOs2OKN2qwC9eAZky6eGgj1d9W0yCdCk-xLsDjJl8DM0d9Z--l0TdYigSdO0t8cNPrDlQCi8z4418mvpC1kmrO3pn2VS5_C8Rty39E-EnBjX_8",
    imageAlt: "Organic soy wax candle on a styled shelf",
    description: "A clean-burning soy candle with a calming botanical fragrance.",
    seoTitle: "Organic Soy Wax Candle Pakistan | PakMarket",
    metaDescription: "Shop a clean-burning organic soy wax candle made by a local Pakistani brand.",
  },
  {
    id: "p5",
    name: "Genuine Leather Wallet",
    slug: "genuine-leather-wallet",
    sku: "PM-LEA-005",
    category: "Leather",
    price: 2400,
    comparePrice: 0,
    stock: 0,
    enabled: true,
    seoIndex: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAsLD4Fq6OiUN5TM_GlEPXoSH2X9jpMvMQ9xlM3aQE1OJp6Dt17qubFE_v47nnS3rE8fTr-bPfqm1dwBuEQqF53g9WTAgk9tCvjVY-lFWg9lHoknSA4_UdgxNtgT8Bbbew-B_q-DUpCnvfrS5L6t9vvQONfziwceB45Ra4H3wQ_Oui7CcCIWr2J0jxTLpna3MeiCQnH85gHCeiSNy9D23LOGrnl95LHuYyI2w1ge91B2OjH2mp1pAExpaWpi-s59Yc8AJNWQ9sOP4g",
    imageAlt: "Genuine leather wallet with visible stitching",
    description: "A slim wallet handcrafted from genuine Pakistani leather.",
    seoTitle: "Genuine Leather Wallet Pakistan | PakMarket",
    metaDescription: "Buy a handcrafted genuine leather wallet from a trusted Pakistani maker.",
  },
  {
    id: "p6",
    name: "Pure Organic Sidr Honey",
    slug: "pure-organic-sidr-honey",
    sku: "PM-ORG-006",
    category: "Organic",
    price: 3500,
    comparePrice: 0,
    stock: 18,
    enabled: false,
    seoIndex: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAOK-RqPQhvR2zujHkgUq4-hnaB6f1OAa43QEQLnPv9Q6tc4JwYO-9dmE3PVcSTS7pr6kGYnsOTJarPpWM7vA9JTaAHEnO_OTFiC87O1lc5wUuKe6qwIjjB8Epqbwa7ZGzKNxg_0elr8kNkFhH_OCoG2ZzoryKI_zx8BG39V0kui3IAUj6WD0qW1TvohZX21pRROU2MFXBvFHFR2hAK7kLJ3viJ93a0abFX7wJnFsVuKcaeNlb7p75UPEbHUP8G7wJfpL8gNSRfe8Q",
    imageAlt: "Organic Sidr honey jar",
    description: "Pure Sidr honey sourced in small batches from trusted local beekeepers.",
    seoTitle: "Pure Organic Sidr Honey in Pakistan | PakMarket",
    metaDescription: "Pure Sidr honey sourced from trusted local beekeepers.",
  },
];
