export const DEFAULT_PRODUCTS = [
  // 1. Custom Bouquets (Physical Deliverable)
  {
    id: "bq-ferrero-rose",
    name: "Imperial Ferrero Rocher & Artificial Rose Bouquet",
    slug: "imperial-ferrero-rocher-rose-bouquet",
    sku: "SD-BQT-001",
    category: "Custom Bouquets",
    price: 4800,
    comparePrice: 5500,
    stock: 25,
    options: [
      { name: "Size & Chocolate Count", required: true, values: ["Standard (12 Chocolates)", "Large (20 Chocolates)", "Deluxe (30 Chocolates)"] },
      { name: "Wrapping Color Theme", required: true, values: ["Rose Gold", "Classic Black & Gold", "Pastel Pink", "Emerald Green"] },
      { name: "Add-on Greeting Card", required: false, values: ["Free Handwritten Note", "None"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Luxury Ferrero Rocher chocolate bouquet with artificial roses",
    description: "Indulge your loved ones with our signature luxury bouquet featuring original Ferrero Rocher hazelnut chocolates nestled among premium artificial silk roses. Finished with imported dual-tone Korean wrapping paper and satin ribbon. 50% advance deposit required for customized assembly.",
    seoTitle: "Imperial Ferrero Rocher & Rose Bouquet | Shah Decorator",
    metaDescription: "Handcrafted Ferrero Rocher chocolate bouquets with artificial roses and custom wrapping in Pakistan. Order on WhatsApp.",
  },
  {
    id: "bq-currency-grand",
    name: "Grand Currency / Money Bouquet",
    slug: "luxury-currency-money-bouquet",
    sku: "SD-BQT-002",
    category: "Custom Bouquets",
    price: 3500,
    comparePrice: 4200,
    stock: 20,
    options: [
      { name: "Note Denomination", required: true, values: ["Rs. 50 Notes (50 Notes)", "Rs. 100 Notes (50 Notes)", "Rs. 500 Notes (30 Notes)", "Rs. 1000 Notes (20 Notes)"] },
      { name: "Theme Palette", required: true, values: ["Royal Gold & Red", "Rose Gold & Blush Pink", "Elegant Black & Gold"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Artisanal currency note bouquet with royal floral accents",
    description: "A spectacular custom currency bouquet crafted with uncirculated crisp notes, artificial gold florals, and designer packaging. Ideal for weddings, Barat gifts, and grand congratulations. 50% advance deposit required.",
    seoTitle: "Custom Currency & Money Bouquet | Shah Decorator",
    metaDescription: "Bespoke money bouquets with fresh banknotes and luxury styling across Pakistan.",
  },

  // 2. Party Supplies & Balloons (Physical Deliverable)
  {
    id: "ps-balloon-arch-kit",
    name: "Premium DIY Balloon Garland & Arch Kit (120 Pcs)",
    slug: "diy-balloon-garland-arch-kit",
    sku: "SD-PRT-001",
    category: "Party & Balloons",
    price: 2200,
    comparePrice: 2800,
    stock: 50,
    options: [
      { name: "Color Theme", required: true, values: ["Rose Gold & White", "Metallic Gold & Black", "Pastel Rainbow", "Jungle Safari"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
    imageAlt: "DIY balloon garland kit with metallic and pastel balloons",
    description: "Complete 120-piece balloon arch kit including dual-size latex balloons, metallic confetti balloons, arch decorating strip, glue dots, and ribbon. Perfect for birthdays, bridal showers, and anniversaries.",
    seoTitle: "DIY Balloon Garland Arch Kit | Shah Decorator",
    metaDescription: "Buy premium DIY balloon garland kits with fast delivery across Pakistan.",
  },
  {
    id: "ps-sash-popper-bundle",
    name: "Celebration Party Poppers & Satin Sash Bundle",
    slug: "party-popper-celebration-sash-bundle",
    sku: "SD-PRT-002",
    category: "Party & Balloons",
    price: 1450,
    comparePrice: 1800,
    stock: 40,
    options: [
      { name: "Sash Title", required: true, values: ["Bride to Be", "Mom to Be", "Birthday Queen", "Groom to Be"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Party poppers and metallic satin celebration sash",
    description: "Premium glittered satin sash with matching foil crown and 4 heavy confetti party poppers. Make entry moments dramatic and festive!",
    seoTitle: "Party Poppers & Celebration Sash Bundle | Shah Decorator",
    metaDescription: "Party accessories, Bride to Be sashes, and metallic poppers for celebrations.",
  },

  // 3. Mayon & Mehndi Essentials (Physical Deliverable)
  {
    id: "mh-thaal-ubtan-set",
    name: "Luxury Decorated Mehndi Thaal & Ubtan Bowl Set",
    slug: "decorated-mehndi-thaal-ubtan-set",
    sku: "SD-MHN-001",
    category: "Mayon & Mehndi Essentials",
    price: 3800,
    comparePrice: 4500,
    stock: 18,
    options: [
      { name: "Decoration Style", required: true, values: ["Royal Gota Kinari", "Floral Velvet", "Traditional Mirror Work"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1545232979-fbf6c9fa19df?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Decorated Mehndi thaal with ubtan bowls and marigold accents",
    description: "Handcrafted wooden/metal Mehndi thaal decorated with gotta laces, mirror work, embedded candle holders, and matching ceramic ubtan bowls for Mayon rituals.",
    seoTitle: "Decorated Mehndi Thaal & Ubtan Set | Shah Decorator",
    metaDescription: "Buy designer Mehndi thaals and Mayun ritual accessories in Pakistan.",
  },
  {
    id: "mh-gota-jewelry-set",
    name: "Handcrafted Gota Jewelry & Dholki Props Set",
    slug: "gota-jewelry-dholki-props-set",
    sku: "SD-MHN-002",
    category: "Mayon & Mehndi Essentials",
    price: 2600,
    comparePrice: 3200,
    stock: 30,
    options: [
      { name: "Jewelry Color", required: true, values: ["Yellow & Green", "Pink & Orange", "Royal Red & Gold"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Handmade gota jewelry set with festive dholki photo props",
    description: "Bridal floral jewelry set including matha patti, earrings, necklace, and hathphool, bundled with 10 vibrant photo booth props for dholki nights.",
    seoTitle: "Gota Jewelry & Dholki Props Set | Shah Decorator",
    metaDescription: "Handcrafted bridal gota jewelry and party props for Pakistani Mehndi celebrations.",
  },

  // 4. Room Decor Services (On-Location Service)
  {
    id: "rm-bridal-suite",
    name: "Bridal & Groom Suite Romantic Decor Package",
    slug: "bridal-groom-suite-romantic-decor",
    sku: "SD-ROM-001",
    category: "Room Decor Services",
    price: 8500,
    comparePrice: 10500,
    stock: 10,
    options: [
      { name: "Package Tier", required: true, values: ["Essential Setup (Rs. 8,500)", "Premium Deluxe (Rs. 14,000)", "Royal Grand (Rs. 22,000)"] },
      { name: "Color Palette", required: true, values: ["Rose Gold & White", "Crimson Red & Warm Gold", "Lavender & Silver"] },
      { name: "Karachi Area / Sector", required: true, values: ["Orangi / Nazimabad", "Gulshan / Johar", "DHA / Clifton", "Other Karachi Area"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Romantic bridal suite room decoration with fairy lights and rose petals",
    description: "Elevate wedding night memories with a professionally styled room decor package. Includes ceiling balloon canopy, hanging fairy lights, fresh rose petals bed styling, ambient LED pillar candles, and marquee letter lights. 50% advance deposit confirms booking.",
    seoTitle: "Bridal & Groom Suite Room Decor | Shah Decorator",
    metaDescription: "Professional romantic room decor for wedding nights and anniversaries in Karachi.",
  },
  {
    id: "rm-bride-to-be",
    name: "Luxury Bride-to-Be Room Surprise Setup",
    slug: "luxury-bride-to-be-room-setup",
    sku: "SD-ROM-002",
    category: "Room Decor Services",
    price: 7500,
    comparePrice: 9500,
    stock: 12,
    options: [
      { name: "Package Tier", required: true, values: ["Standard Glow (Rs. 7,500)", "Deluxe Celebration (Rs. 12,000)"] },
      { name: "Theme Palette", required: true, values: ["Rose Gold & White Pearl", "Champagne Gold & Pink"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Bride to be room surprise setup with foil banner and lights",
    description: "Surprise the bride with custom 'Bride to Be' foil balloons, floor balloon clusters, twinkle string backdrops, photo banner strings, and entrance walkway decor.",
    seoTitle: "Bride to Be Room Decor Package | Shah Decorator",
    metaDescription: "Stunning Bride to Be room surprise setups and bridal shower decor in Karachi.",
  },

  // 5. Event & Stage Decor (On-Location Service)
  {
    id: "ev-mehndi-stage",
    name: "Bespoke Mehndi & Mayun Stage Setup",
    slug: "bespoke-mehndi-mayun-stage-setup",
    sku: "SD-EVT-001",
    category: "Event & Stage Decor",
    price: 28000,
    comparePrice: 35000,
    stock: 6,
    options: [
      { name: "Stage Tier", required: true, values: ["Classic Marigold Jhula (Rs. 28,000)", "Royal Floral Stage (Rs. 45,000)", "Grand Palace Theme (Rs. 75,000)"] },
      { name: "Theme Colors", required: true, values: ["Festive Yellow & Green", "Vibrant Multi-Color", "Mustard & Orange"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Mehndi stage setup with floral swing and traditional drapes",
    description: "Complete festive Mehndi stage setup including floral jhula swing, vibrant drapes, stage riser carpet, cushion seating lounge, Moroccan lamps, and warm spotlights.",
    seoTitle: "Mehndi & Mayun Stage Decor Setup | Shah Decorator",
    metaDescription: "Book festive Mehndi stages, jhulas, and traditional decor in Karachi.",
  },
  {
    id: "ev-birthday-backdrop",
    name: "Theme Birthday & Baby Shower Backdrop Setup",
    slug: "baby-shower-birthday-backdrop-setup",
    sku: "SD-EVT-002",
    category: "Event & Stage Decor",
    price: 12500,
    comparePrice: 16000,
    stock: 8,
    options: [
      { name: "Theme", required: true, values: ["Pastel Balloon Arch & Neon", "Jungle Safari Theme", "Princess Castle Pink", "Teddy Bear & Cloud Welcome"] },
    ],
    enabled: true,
    seoIndex: true,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Birthday and baby shower backdrop setup with balloon arch",
    description: "Customized round or rectangular backdrop with organic balloon garlands, custom neon sign, cake plinths, and character cutouts for birthdays and baby arrivals.",
    seoTitle: "Birthday & Baby Shower Backdrop Setup | Shah Decorator",
    metaDescription: "Custom theme birthday and baby shower stage setups in Karachi by Shah Decorator.",
  },
];
